-- QUERY 1
SELECT AGENCY, COUNT(*) AS EMP_COUNT
FROM HR_DEPARTMENT
GROUP BY AGENCY;
--END

--QUERY 2 
SELECT "Employee Name" FROM HR_DEPARTMENT
WHERE "Position Title" = 'CONTRACTUAL WORKER';
--END

--QUERY 3
SELECT "Employee Name" FROM HR_DEPARTMENT
WHERE AGENCY = 'ABE LINCOLN PRES LIBRARY & MUS';
--END

--QUERY 4
SELECT "Position Title",COUNT(*) EMP_COUNT FROM HR_DEPARTMENT 
GROUP BY "Position Title";
--END

--QUERY 5
SELECT COUNT(*) EMP_COUNT FROM HR_DEPARTMENT
WHERE "Period Pay Rate" <50000 ;
--END